
title: Wead.
email: your-email@domain.com
description: "A simple and clean jekyll theme."
twitter_username: kevyder
github_username:  kevyder
baseurl: /wade

markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
